name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libjson-c-dev

      - name: Build for ${{ matrix.arch }}
        run: |
          mkdir -p build
          gcc -Wall -Wextra -I/usr/include/json-c -c -o build/main.o main.c
          gcc -Wall -Wextra -I/usr/include/json-c -c -o build/actions.o actions.c
          gcc -Wall -Wextra -I/usr/include/json-c -c -o build/database.o database.c
          gcc build/main.o build/actions.o build/database.o -ljson-c -o build/sshtool-${{ matrix.arch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: sshtool-${{ matrix.arch }}
          path: build/sshtool-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries x86_64
        uses: actions/download-artifact@v2
        with:
          name: sshtool-x86_64
          path: build/

      - name: Download binaries arm64
        uses: actions/download-artifact@v2
        with:
          name: sshtool-arm64
          path: build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/sshtool-x86_64
            build/sshtool-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
